#!/usr/bin/env bash
set +o posix

###====: HOMERECIPE :============================================
###      Recipe to cook my $HOME
###==============================================================

#------: Main Logic :--------------------------------------------
# The logic is really simple - this "cook" executable
#   will kick off shell scripts under core/scripts/ directory.
#
# All the main business logic is under each script.
# util.sh provides some defaulting and catching missing params.
#
#------: Special Thanks :----------------------------------------
# Some of the base logic for this "cook" came from
#   the ideas of Homebrew https://github.com/Homebrew/brew
#----------------------------------------------------------------

quiet_cd() {
  cd "$@" >/dev/null || echo "Error: cd failed, could not locate the dir"
}
export HOMERECIPE_DIR
HOMERECIPE_DIR="$(quiet_cd "${0%/*}" && pwd -P)"
export HOMERECIPE_FILE="${HOMERECIPE_DIR%/}/${0##*/}"
export HOMERECIPE_SCRIPTS="${HOMERECIPE_DIR%/}/core/scripts/"
export HOMERECIPE_PREFIX="${HOMERECIPE_FILE%/*/*}"

case "$1" in
  h)          COOKWARE="prompt_help" ;;
  -h)         COOKWARE="prompt_help" ;;
  --h)        COOKWARE="prompt_help" ;;
  help)       COOKWARE="prompt_help" ;;
  debug)      COOKWARE="debug" ;;

  setup)      COOKWARE="${HOMERECIPE_SCRIPTS}/setup.sh" ;;
  check)      COOKWARE="${HOMERECIPE_SCRIPTS}/check-updates.sh" ;;

  # dotfiles
  map)        COOKWARE="${HOMERECIPE_SCRIPTS}/cook-dotfiles.sh" ;;
  dotfiles)   COOKWARE="${HOMERECIPE_SCRIPTS}/cook-dotfiles.sh" ;;
  rmdotfiles) COOKWARE="${HOMERECIPE_SCRIPTS}/remove-dotfiles.sh" ;;

  # recipes
  recipes)    COOKWARE="${HOMERECIPE_SCRIPTS}/cook-recipes.sh" ;;
  prep)       COOKWARE="${HOMERECIPE_SCRIPTS}/make-recipes.sh" ;;
  backup)     COOKWARE="${HOMERECIPE_SCRIPTS}/make-recipes.sh" ;;
  rmrecipes)  COOKWARE="${HOMERECIPE_SCRIPTS}/remove-recipes.sh" ;;
  list)       COOKWARE="${HOMERECIPE_SCRIPTS}/list-recipes.sh" ;;

  # other
  all)        COOKWARE="${HOMERECIPE_SCRIPTS}/run-all.sh" ;;
  restore)    COOKWARE="${HOMERECIPE_SCRIPTS}/run-all.sh -f" ;;
  remove)     COOKWARE="${HOMERECIPE_SCRIPTS}/remove-defaults.sh" ;;

  custom)     COOKWARE="${HOMERECIPE_DIR}/custom/run-custom.sh"
esac
shift

debug() {
  echo "Debug information"
  echo
  echo "HOMERECIPE_DIR : $HOMERECIPE_DIR"
  echo "HOMERECIPE_FILE : $HOMERECIPE_FILE"
  echo "HOMERECIPE_SCRIPTS : $HOMERECIPE_SCRIPTS"
  echo "HOMERECIPE_PREFIX : $HOMERECIPE_PREFIX"
  echo "COOKWARE : $COOKWARE"
  echo "Extra Arg : $*"
  echo
  echo "HOMERECIPE_MODE: $HOMERECIPE_MODE"
  echo "HOMERECIPE_ZSH_INSTALL: $HOMERECIPE_ZSH_INSTALL"
}

prompt_help() {
  local help
  read -rd '' help <<-EOF
Homerecipe
Shell-crafted tool to help manage your \$HOME

  Before starting:
    cook setup            -- set up Hommerecipe (copy .homerecipe to $HOME)

  Main usage:
    cook check            -- check if you have the current latest files
    cook recipes          -- cook recipes under $HOMERECIPE_DIR/recipes/ directory
    cook dotfiles [-f]    -- map dotfiles to $HOME

    cook all              -- cook recipes, map dotfiles,
                             kick off run-custom if exist,
                             and symlink .homerecipe
    cook restore          -- the same as 'cook all -f'

    cook [prep|backup]    -- make recipes, overriding the existing contents

    cook list             -- list all recipes and their contents

    cook remove           -- remove default recipes and dotfiles

    cook help             -- show this message

  Custom usage:
    cook custom           -- kicks off $HOMERECIPE_DIR/misc/run-custom.sh
                             only if it exists

  Alias support:
    .homerecipe provides aliases: cook, cookdir

  Note:
    use -f with caution, you can delete existing dotfiles under \$HOME
EOF
  echo "$help"
}

if [[ -r $COOKWARE ]]
then
  $COOKWARE "$@"
elif [[ ! -z $COOKWARE ]]
then
  $COOKWARE
else
  echo "Error - specified command not found"
  echo ""
  prompt_help && exit 1
fi
